# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Heather Savoy
email: frystacka@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  This site describes my research at Berkeley for my PhD in 
  Civil and Environmental Engineering related to geostatistics,
  inverse modeling, aquifer characterization, and open-source
  scientific computing. 
baseurl: "/hsavoy.github.io" # the subpath of your site, e.g. /blog
url: "http://hsavoy.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  hsavoy

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-paginate
  - jekyll-coffeescript
  # other gems
